In [21]:
import torch

In [22]:
a=torch.randint(1,5,(2,3))
b=torch.randint(1,5,(2,3))
print(a)
print(b)

tensor([[1, 2, 4],
        [2, 2, 3]])
tensor([[3, 2, 1],
        [4, 3, 4]])


In [23]:
a+b

tensor([[4, 4, 5],
        [6, 5, 7]])

In [24]:
torch.add(a,b)

tensor([[4, 4, 5],
        [6, 5, 7]])

In [25]:
result=torch.zeros(2,3)
torch.add(a,b,out=result)

tensor([[4., 4., 5.],
        [6., 5., 7.]])

In [26]:
#a=a+b
#hint:tensor changing by any operated will keep '_' before function, as a.add_() , b.sub_()
a.add_(b)

tensor([[4, 4, 5],
        [6, 5, 7]])

In [27]:
a-b

tensor([[1, 2, 4],
        [2, 2, 3]])

In [28]:
a*b

tensor([[12,  8,  5],
        [24, 15, 28]])

In [29]:
a/b

tensor([[1.3333, 2.0000, 5.0000],
        [1.5000, 1.6667, 1.7500]])

In [30]:
a%b

tensor([[1, 0, 0],
        [2, 2, 3]])

In [31]:
#取整
a//b

tensor([[1, 2, 5],
        [1, 1, 1]])

In [32]:
tensor =torch.ones(3,5)
tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [15]:
a

tensor([[ 6,  7,  9],
        [ 7, 11,  3]])

In [16]:
torch.matmul(a, tensor)

RuntimeError: expected m1 and m2 to have the same dtype, but got: __int64 != float

In [17]:
a.dtype

torch.int64

In [18]:
tensor.dtype

torch.float32

In [19]:
a=a.float()
a.dtype

torch.float32

In [20]:
torch.matmul(a,tensor)

tensor([[22., 22., 22., 22., 22.],
        [21., 21., 21., 21., 21.]])