In [1]:
import torch

In [2]:
sample=torch.rand(3,2)
sample

tensor([[0.0887, 0.7636],
        [0.2302, 0.5587],
        [0.8047, 0.9952]])

In [3]:
torch.sum(sample)

tensor(3.4411)

In [4]:
torch.min(sample)

tensor(0.0887)

In [5]:
torch.max(sample)

tensor(0.9952)

In [6]:
torch.argmin(sample)

tensor(0)

In [7]:
torch.argmax(sample)

tensor(5)

In [8]:
torch.mean(sample)

tensor(0.5735)

In [9]:
torch.median(sample)

tensor(0.5587)

In [10]:
torch.sqrt(sample)

tensor([[0.2979, 0.8739],
        [0.4798, 0.7475],
        [0.8970, 0.9976]])

In [11]:
print(sample**2)
print(sample**3)


tensor([[0.0079, 0.5832],
        [0.0530, 0.3121],
        [0.6475, 0.9904]])
tensor([[6.9888e-04, 4.4532e-01],
        [1.2199e-02, 1.7438e-01],
        [5.2105e-01, 9.8563e-01]])
